
user_home: "/home/{{ user }}"

nfs_mount_path: "/nas"

downloads_path: "/downloads"

supervisord_config_path: "/etc/supervisor/conf.d"

deluge_config_path: "{{ user_home }}/.deluge"

sabnzb_config_path: "{{ user_home }}/.sabnzb"

sickbeard_app_path: "{{ user_home }}/Apps/sickbeard"
sickbeard_config_path: "{{ user_home }}/.sickbeard"

couchpotato_app_path: "{{ user_home }}/Apps/couchpotato"
couchpotato_config_path: "{{ user_home }}/.couchpotato"

htpc_manager_app_path: "{{ user_home }}/Apps/htpc_manager"
htpc_manager_config_path: "{{ user_home }}/.htpc_manager"
