---

- name: aliases.sh script in place
  copy: src=aliases.sh dest=/home/{{user}}/.bashrc.d/aliases.sh owner={{user}} group={{user}} mode=0744

- name: aliases installed
  lineinfile: dest=/home/{{user}}/.bashrc line=". ~/.bashrc.d/aliases.sh"
