---

- name: ssh-agent.sh script in place
  copy: src=ssh-agent.sh dest=/home/{{user}}/.bashrc.d/ssh-agent.sh owner={{user}} group={{user}} mode=0744

- name: Sourced ssh-agent.sh from barchrc
  lineinfile: dest=/home/{{user}}/.bashrc line=". ~/.bashrc.d/ssh-agent.sh"
