---

- name: State of Oracle JDK installation
  sudo: true
  stat: path=/usr/lib/jvm/java-7-oracle
  register: java

- name: JDK repo installed
  sudo: true
  apt_repository: repo=ppa:webupd8team/java
  when: not java.stat.exists

- name: Agreed to Oracle license
  sudo: true
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
  when: not java.stat.exists

- name: JDK 7 package installed
  sudo: true
  apt: pkg=oracle-java7-installer state=latest
  when: not java.stat.exists
