---
- hosts: local
  connection: local
  sudo: false

  roles:
    - common
    - profile
    - sdk-python
    - sdk-nodejs
    - sdk-java
    - ide-pycharm
    - ide-sublime
    - server-redis
    - server-mysql
    - browser-chrome
    - vbox-guest
    - desktop-i3
#    - laptop-ux32vd
