---

# To run:
# ansible-playbook -K -i inventory dev-machine.yml --tags=tags

- hosts: local
  connection: local
  sudo: false

  roles:
    - role: common
      tags: common

    - role: profile
      tags: profile

    - role: sdk-python
      tags: python

    - role: sdk-virtualbox
      tags: virtualbox

    - role: server-vagrant
      tags: vagrant

    - role: sdk-nodejs
      tags: nodejs

    - role: sdk-java
      tags: java

    - role: ide-pycharm
      tags: pycharm

    - role: ide-datagrip
      tags: datagrip

    - role: ide-pgadmin3
      tags: pgadmin3

    - role: ide-intellij
      tags: intellij

    - role: ide-atom
      tags: atom

    - role: server-redis
      tags: redis

    - role: sdk-mysql
      tags: mysql-client

    - role: server-docker
      tags: docker

    - role: browser-chrome
      tags: chrome

    - role: desktop-i3
      tags: i3

    - role: desktop-kodi
      tags: kodi

    - role: laptop-ux32vd
      tags: ux32vd
