---

# To run: 
# ansible-playbook -K -i inventory dev-machine.yml --tags=tags

- hosts: local
  connection: local
  sudo: false

  roles:
    - role: common
      tags: common

    - role: profile
      tags: profile

    - role: sdk-python
      tags: python

#    - role: sdk-virtualbox
#      tags: virtualbox

    - role: sdk-nodejs
      tags: nodejs

    - role: sdk-java
      tags: java

    - role: ide-pycharm
      tags: pycharm

    - role: server-redis
      tags: redis

    - role: sdk-mysql
      tags: mysql-client

    - role: server-docker
      tags: docker

    - role: browser-chrome
      tags: chrome

    - role: desktop-i3
      tags: i3

#    - role: laptop-ux32vd
#      tags: ux32vd
