---
## See Makefile

- hosts: nuc
  sudo: false

  roles:

    - role: remote-user
      tags: bootstrap

    - role: server-sshd
      tags: bootstrap

    - role: common
      tags: common

    - role: server-supervisord
      tags: supervisord

    - role: server-nuc
      tags: nuc
