---

- name: secure sshd
  lineinfile: >
    dest=/etc/ssh/sshd_config
    state=present
    regexp='^#?{{ item.key }}'
    line='{{ item.key }} {{ item.value }}'
    validate='/usr/sbin/sshd -t -f %s'
    backup=yes
  with_items:
    - { key: 'Port',                   value: "{{ sshd_port }}"}
    - { key: 'PermitRootLogin',        value: "no"}
    - { key: 'PasswordAuthentication', value: "no"}
    - { key: 'AllowGroups',            value: "sudo"}
    - { key: 'MaxAuthTries',           value: "5"}
    - { key: 'LoginGraceTime',         value: "60"}
    - { key: 'MaxSessions',            value: "5"}
    - { key: 'MaxStartups',            value: "10:30:60"}
    - { key: 'UseDNS',                 value: "no"}

  notify: restart sshd
  sudo: true
