---

- name: NodeJS repo installed
  sudo: true
  apt_repository: repo=ppa:chris-lea/node.js

- name: NodeJS installed
  sudo: true
  apt: pkg=nodejs state=latest

- name: Grunt-cli installed
  sudo: true
  npm: name=grunt-cli global=yes state=latest
