---

- name: download folders exist
  file:
    path: "{{ downloads_path }}/{{ item }}"
    state: directory
    owner: "{{user}}"
  with_items:
    - ForCouchpotato
    - ForSickrage
    - ForSabnzb
    - ForDeluge
    - Archive/NZB
    - Archive/Torrent
    - Incomplete/Sabnzbd
    - Incomplete/Deluge
