---

- include: supervisord.yml tags=supervirsord
- include: nfs_share.yml tags=nfs
- include: kodi.yml tags=kodi
- include: deluge.yml tags=deluge
- include: sabnzb.yml tags=sabnzb
- include: sickrage.yml tags=sickrage
- include: couchpotato.yml tags=couchpotato
- include: htpc_manager.yml tags=htpc_manager
