---

- name: sickrage dependencies installed
  sudo: true
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - python-cheetah

- name: clone sickrage
  git:
    accept_hostkey: yes
    clone: yes
    repo: https://github.com/SiCKRAGETV/SickRage.git
    version: master
    dest: "{{ sickrage_app_path }}"

- name: configure webroot
  lineinfile:
    create: yes
    dest: "{{ sickrage_config_path }}/config.ini"
    regexp: "^web_root"
    line: 'web_root = "/shows"'

- name: sickrage supervisord conf
  sudo: true
  template:
    src: sickrage.conf.j2
    dest: "{{ supervisord_config_path }}/sickrage.conf"

- name: supervisord update
  sudo: true
  command: supervisorctl update

- name: start sickrage
  sudo: true
  supervisorctl:
    name: sickrage
    state: started
