---

- name: oracle key installed
  sudo: true
  apt_key:
    state: present
    url: 'http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc'

- name: virtualbox repo present
  apt_repository:
    repo: 'deb http://download.virtualbox.org/virtualbox/debian {{ansible_distribution_release}} contrib'
  sudo: true

- name: virtual box & dependencies
  sudo: true
  apt:
    pkg: "{{item}}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - dkms
    - virtualbox
    - virtualbox-dkms
