---

- name: ensure user exists
  user: name={{ user }}
    state=present
    password={{ user_password }}
    shell=/bin/bash
    groups=adm,sudo,plugdev,cdrom
    append=yes
  sudo: true

- name: ensure ssh key
  authorized_key: user={{ user }} key=https://github.com/{{ github_username }}.keys exclusive=yes
  sudo: true

- name: remove the default user {item}
  user: name={item} remove=yes state=absent
  when: ansible_ssh_user != '{item}'
  sudo: true
  with_items:
    - ubuntu
    - pi

- name: remove /home/{item}
  file: path=/home/ubuntu state=absent
  when: ansible_ssh_user != '{item}'
  sudo: true
  with_items:
    - ubuntu
    - pi
