---

- name: I3 config dir present
  file: path=/home/{{user}}/.i3 state=directory owner={{user}} mode=0755

- name: I3 package installed
  sudo: true
  apt: pkg=i3 state=latest update_cache=yes

- name: I3 Config file
  copy: src=config dest=/home/{{user}}/.i3/config owner={{user}} group={{user}} mode=0644

- name: I3 Status Config file
  copy: src=.i3status.conf dest=/home/{{user}}/.i3status.conf owner={{user}} group={{user}} mode=0644

- include: wallpapers.yml
