---

- name: Stat PyCharm dir
  sudo: true
  stat: path=/home/{{user}}/Apps/pycharm-{{pycharm_version}}
  register: pycharm

- name: PyCharm downloaded
  get_url: url="http://download.jetbrains.com/python/pycharm-professional-{{pycharm_version}}.tar.gz" dest=/tmp/pycharm.tar.gz
  when: not pycharm.stat.exists

- name: PyCharm installed
  command: tar -xzf /tmp/pycharm.tar.gz -C /home/{{user}}/Apps/
  when: not pycharm.stat.exists

- name: PyCharm menu item
  sudo: true
  template: src=pycharm.desktop.j2 dest=/usr/share/applications/pycharm.desktop mode=0644
