---

- name: Python specific packages installed
  sudo: true
  apt: pkg={{item}} state=latest
  with_items:
    - python-pip
    - python-dev


- name: Virtualenv wrapper installed
  pip: name=virtualenvwrapper state=latest

- name: Virtualenv wrapper configured
  copy: src=virtualenvwrapper.sh dest=/home/{{user}}/.bashrc.d/virtualenvwrapper.sh owner={{user}} group={{user}} mode=0644

- name: System iPython installed
  sudo: true
  pip: name=ipython state=latest