---

- name: python packages installed
  sudo: true
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - python-pip
    - python-dev

- name: upgrade pip installed
  sudo: true
  pip:
    name: pip
    state: latest

- name: virtualenv installed
  sudo: true
  pip:
    name: virtualenv
    state: latest

#- name: virtualenv wrapper configured
#  copy:
#    src: virtualenvwrapper.sh
#    dest: /home/{{user}}/.bashrc.d/virtualenvwrapper.sh
#    owner: "{{ usear }}"
#    group: "{{ user }}"
#    mode: 0644
#
#- name: sourced virtualenvwrapper.sh from barchrc
#  lineinfile:
#    dest: "/home/{{user}}/.bashrc"
#    line: ". ~/.bashrc.d/virtualenvwrapper.sh"
#
#- name: system ipython installed
#  sudo: true
#  pip:
#    name: ipython
#    state: latest
