---

- name: install latest kernel for ibuntu 13.04+
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - "linux-image-extra-{{ ansible_kernel }}"
    - linux-image-extra-virtual
  sudo: true

- name: add docker repository key
  apt_key:
    id: "2C52609D"
    url: "https://apt.dockerproject.org/gpg"
    state: present
  sudo: true

- name: add docker repository and update apt cache
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"
    update_cache: yes
    state: present
  sudo: true

- name: install (or update) docker package
  apt:
    name: "docker-engine"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  sudo: true

- name: add user to the docker group
  user:
    name:   "{{ user }}"
    groups: docker
    append: yes
  sudo: true
